feat: add metrics to repo overview
mergestat/mergestat pull request #414
Opened 2022-10-20 10:57 UTC by emilyvandewalle

- Started adding top metrics
- I was able to figure out the `Number of repos` and `Avg number of syncs`, but not `Avg sync time` for which I could use some help

![image](https://user-images.githubusercontent.com/36261498/196929810-cd652f0d-0a44-44d0-a4a1-d4808aeb4fd7.png)

(Resolves #222)

2022-10-21 22:08 UTC, patrickdevivo commented
This looks great! @amenowanna and I discussed a bit and we wanted to change the numbers a bit. Implementation may need to involve @german-mergestat too, so tagging him in. But overall look and feel wise looks great.

The numbers should be:
- Total number of repos (stays the same)
- Total number of repo syncs (i.e. the sum of all the "sum" values in the table)
- Total number of repo syncs where the latest run had an error (i.e. the sum of all the "error" values in the table)

The other ask is to see if we can move the repo search bar to _below_ these numbers, to make it clear that they are global totals (and that searching does not change them). Thanks so much @emilyvandewalle

2022-10-25 13:18 UTC, amenowanna commented
Looks great! My only comment here is that the titles of each metric is using different wording. Can we make it consistent please. Like `Total number of...` or `Number of...` @patrickdevivo have a preference?

2022-10-25 13:30 UTC, emilyvandewalle commented
Oops, good catch, agree this should be consistent, adjusted it to `Total number of...` ! 👍

2022-10-25 16:47 UTC, emilyvandewalle commented
(I was a bit too fast in trying to adjust it, I'll wait for @patrickdevivo to give his preference)

2022-10-25 17:54 UTC, patrickdevivo commented
(Copied from Slack)

- Let’s change the text to just say Total repos Total repo syncs and Latest syncs with errors
- Let’s add a loading/indeterminate state for  the “metric box” when the data is fetching from the API (you can trigger this by writing a search query - tho these should be unrelated, I think we should actually pull them out into separate queries, especially since pagination will change that list-repos query)
- Finally the last box (Latest syncs with errors) needs to be implemented data wise

I think once those are addressed it should be good to merge!

2022-10-27 02:34 UTC, patrickdevivo commented
```graphql
query {
  repos {
    totalCount
  }
  repoSyncs(condition: {scheduleEnabled: true}) {
    totalCount
  }
  execSQL(query: "WITH ranked_completed_syncs AS ( SELECT rsq.id, rsq.repo_sync_id, rsq.done_at, RANK() OVER(PARTITION BY rsq.repo_sync_id ORDER BY rsq.done_at DESC) AS rank_num FROM mergestat.repo_sync_queue AS rsq WHERE rsq.repo_sync_id NOT IN (SELECT repo_sync_id FROM mergestat.repo_sync_queue WHERE status = 'RUNNING' OR status = 'QUEUED') ) SELECT COUNT(DISTINCT rcs.id) AS syncs_error_count FROM ranked_completed_syncs AS rcs INNER JOIN mergestat.repo_sync_logs AS rsl ON rcs.id = rsl.repo_sync_queue_id WHERE rank_num = 1 AND log_type = 'ERROR'")
}
```

2022-10-27 02:34 UTC, patrickdevivo commented
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/57259/198177338-0e3057ed-86fc-4e73-92fa-77b80e1ae4ab.png">

2022-10-27 19:26 UTC, patrickdevivo requested changes

2022-10-27 19:26 UTC, patrickdevivo commented on ui/src/views/repositories/index.tsx
> +                <Stat.Label>Latest syncs with errors</Stat.Label>
```suggestion
                <Stat.Label>Total syncs with errors</Stat.Label>
```

2022-10-27 19:39 UTC, german-mergestat commented on ui/src/views/repositories/index.tsx
> +                <Stat.Label>Latest syncs with errors</Stat.Label>
Done [4d2715a](https://github.com/mergestat/mergestat/pull/414/commits/4d2715a2d33d47e1f4d444176bcbe34426c762e9)

2022-10-27 19:44 UTC, patrickdevivo approved these changes

2022-10-27 19:46 UTC, merged